apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
spec:
  containers:
  - image: ec2-52-59-254-8.eu-central-1.compute.amazonaws.com:5000/nodejs
    name: nodejs
    volumeMounts:
    - mountPath: /maven
      name: app-volume
    ports:
    - containerPort: 8999
      hostPort: 8002
  volumes:
  - name: app-volume
    hostPath:
      path: /maven

