apiVersion: v1
kind: List
items:
  - kind: Service
    apiVersion: v1
    metadata:
      name: tomcat-proxy
      annotations:
        http-proxy-servers: '[{"host": "91.237.107.206"}]'
    spec:
      selector:
        name: tomcat
      ports:
        - port: 80
          targetPort: 8080
  - kind: Service
    apiVersion: v1
    metadata:
      name: nodejs-proxy
      annotations:
        http-proxy-servers: '[{"host": "91.237.107.206", "port":"8003", "targetPort":"8003"}]'
    spec:
      selector:
        name: nodejs
      ports:
        - port: 8003
          targetPort: 8999
